name: Go_package_test_run

on:
  pull_request: # Defines when the workflow should run
    branches: 
      - main # Runs on main
  push:
    branches: 
      - 'dev*' # Runs when there is a push to a branch that starts with 'dev'
      - main # Runs when there is a push to main

jobs:
  build: # A job to buld and test the go package
    runs-on: ubuntu-latest # Virtual machine
    steps:
      - uses: actions/checkout@v3 #  Step to check out the repository using a GitHub Actions

      - name: Set up Go # step to set up go 
        uses: actions/setup-go@v4 # github action to set up go
        with:
          go-version: '1.20.4' # Go version to use

      - name: Build
        run: go build -v ./... # run 'go buld' command

      - name: Test
        run: go test -v ./... # run 'go test' command
